name: Deployment to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - apps/playground/**

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/lint.yml

  deploy:
    needs:
      - linter

    runs-on: ubuntu-latest

    concurrency: deployment

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Build page
        run: npm run build-storybook -w @nanlabs/playground

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/playground/storybook-static
